name: Build and Validate Blender Add-on

on:
  workflow_dispatch:
    
jobs:
  build_and_validate:
      name: Build and Validate
      runs-on: ubuntu-latest
      steps: 
        - name: Install Blender
          run: sudo snap install blender --classic
        - name: Clone Repo
          uses: actions/checkout@v4
        - name: Check Binary
          run: snap list
        - name: List bin
          run: ls -la /snap/bin/
        - name: Build
          run: |
            blender --command extension build
        - name: Validate
          run: |
            blender --command extension validate *.zip
                
